ERPElectrodata/Models/QUESTION.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        public QUESTION()
        {
            this.QUESTION_OPTION = new HashSet<QUESTION_OPTION>();
            this.QUESTION_PERSON_ENTITY = new HashSet<QUESTION_PERSON_ENTITY>();
        }
    
        public int ID_QUES { get; set; }
        public Nullable<int> ID_QUES_GROU { get; set; }
        public Nullable<int> ID_QUES_TYPE { get; set; }
        public string NAM_QUES { get; set; }
    
        public virtual ICollection<QUESTION_OPTION> QUESTION_OPTION { get; set; }
        public virtual ICollection<QUESTION_PERSON_ENTITY> QUESTION_PERSON_ENTITY { get; set; }
        public virtual QUESTION_GROUP QUESTION_GROUP { get; set; }
        public virtual QUESTION_TYPE QUESTION_TYPE { get; set; }
    }
}

ERPElectrodata/Models/QUESTION_TYPE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_TYPE
    {
        public QUESTION_TYPE()
        {
            this.QUESTIONs = new HashSet<QUESTION>();
        }
    
        public int ID_QUES_TYPE { get; set; }
        public string NAM_QUES_TYPE { get; set; }
    
        public virtual ICollection<QUESTION> QUESTIONs { get; set; }
    }
}

ERPElectrodata/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERPElectrodata.Models;

namespace ERPElectrodata.Controllers
{
    public class QuestionController : Controller
    {
        public CoreEntities db = new CoreEntities();
       
        // GET: /Question/

        public ActionResult Index()
        {
            List<QUESTION> listquestion = new List<QUESTION>();
            //listquestion = db.QUESTIONs.ToList();
            return View(listquestion);
        }

 //------------------CREATE---------------------------------------       
        public ActionResult Create()
        {
            var newquestion = new QUESTION();          

            return View(newquestion);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveCreate(QUESTION q)
        {
            
            //db.QUESTIONs.Add(q);
            //db.SaveChanges();

           return Redirect("Index");            
              
        }
             
 //---------------------------EDIT----------------------------------------      
        public ActionResult Edit(int id =0)
        {
            var editquestion = new QUESTION();
            //editquestion = db.QUESTIONs.Single(q => q.ID_QUES == id);

            return View(editquestion);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveEdit(QUESTION q)
        {
            var quest = new QUESTION();
             //quest = db.QUESTIONs.Single(qe => qe.ID_QUES==q.ID_QUES);
                     
            quest.NAM_QUES = q.NAM_QUES;
            //quest.DES_QUES = q.DES_QUES;
            //quest.STA_QUES = q.STA_QUES;
            
            UpdateModel(quest);
            db.SaveChanges();

            return Redirect("Index");

        }
        public ActionResult Delete(int id = 0)
        {
            var quest = new QUESTION();
            //quest = db.QUESTIONs.Single(qe =>qe.ID_QUES==id);
            return View(quest);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteQuestion(QUESTION q)
        {
            var questdel = new QUESTION();
            //questdel = db.QUESTIONs.Single(qe => qe.ID_QUES == q.ID_QUES);

            //db.QUESTIONs.Remove(questdel);
            db.SaveChanges();

            return Redirect("Index");

        }
    }
}

ERPElectrodata/Views/Question/Create.cshtml
@model ERPElectrodata.Models.QUESTION

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("SaveCreate", "Question", FormMethod.Post, new { id = "idFormQuest", target = "upload_target" }))
{
   
    <fieldset>
        <legend>QUESTION</legend>

        

        <div class="editor-label">
            @Html.Label("QUESTION NAME") 
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NAM_QUES)
            @Html.ValidationMessageFor(model => model.NAM_QUES)
        </div>

        <div class="editor-label">
            @Html.Label("DESCRIPTION NAME") 
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DES_QUES)
            @Html.ValidationMessageFor(model => model.DES_QUES)
        </div>

        <div class="editor-label">
            @Html.Label("SATATE QUESTION")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.STA_QUES)
            @Html.ValidationMessageFor(model => model.STA_QUES)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ERPElectrodata/Views/Question/Delete.cshtml
@model ERPElectrodata.Models.QUESTION

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
@using (Html.BeginForm("DeleteQuestion", "Question", FormMethod.Post, new { id = "idFormQuestdel", target = "upload_target" }))
{

<fieldset>
    <legend>QUESTION</legend>
    @Html.HiddenFor(model => model.ID_QUES)
    <div class="display-label">
       @Html.Label("ID")       
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ID_QUES)
    </div>

    <div class="display-label">
        @Html.Label("QUESTION NAME")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NAM_QUES)
    </div>

    <div class="display-label">
        @Html.Label("DESCRIPTION QUESTION")
        
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DES_QUES)
    </div>

    <div class="display-label">
        @Html.Label("SATATE QUESTION")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.STA_QUES)
    </div>
</fieldset>

    <p>
        <input type="submit" value="Delete" /> |
        
    </p>
}
@Html.ActionLink("Back to List", "Index")
@*@using (Html.BeginForm("DeleteQuestion", "Question", FormMethod.Post, new { id = "idFormQuestdel", target = "upload_target" }))
{*@

ERPElectrodata/Views/Question/Edit.cshtml
@model ERPElectrodata.Models.QUESTION

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
@using (Html.BeginForm("SaveEdit", "Question", FormMethod.Post, new { id = "idFormedit", target = "upload_target" }))
{
    <fieldset>
        <legend>QUESTION</legend>

        
        <div class="editor-field">
            @Html.HiddenFor(model => model.ID_QUES)
          
        </div>

        <div class="editor-label">
            @Html.Label("QUESTION NAME")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NAM_QUES)
            @Html.ValidationMessageFor(model => model.NAM_QUES)
        </div>

        <div class="editor-label">
            @Html.Label("DESCRIPTION QUESTION")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DES_QUES)
            @Html.ValidationMessageFor(model => model.DES_QUES)
        </div>

        <div class="editor-label">
            @Html.Label("SATATE QUESTION")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.STA_QUES)
            @Html.ValidationMessageFor(model => model.STA_QUES)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ERPElectrodata/Views/Question/Index.cshtml
@model IEnumerable<ERPElectrodata.Models.QUESTION>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LIST OF QUESTIONS</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
           ID
        </th>
        <th>
           QUESTION NAME
        </th>
        <th>
           QUESTION DESCRIPTION
        </th>
        <th>
            STATUS QUESTION
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID_QUES)   
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NAM_QUES)  
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DES_QUES)  
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.STA_QUES)  
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {  id=item.ID_QUES }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID_QUES  })
        </td>
    </tr>
}

</table>