ERPElectrodata/Models/EVALUATION_STAFF.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVALUATION_STAFF
    {
        public EVALUATION_STAFF()
        {
            this.DETAIL_EVALUATION_STAFF = new HashSet<DETAIL_EVALUATION_STAFF>();
            this.OBJECT_BY_STAFF = new HashSet<OBJECT_BY_STAFF>();
        }
    
        public int ID_EVAL_STAF { get; set; }
        public int ID_EVAL { get; set; }
        public Nullable<int> EVA_TIME { get; set; }
        public Nullable<int> NUM_EMPL_EVAL { get; set; }
        public Nullable<int> NUM_EMPL_EVAL_UEN { get; set; }
        public Nullable<int> NUM_EMPL_EVAL_AREA { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> UserId { get; set; }
        public string COM_EVAL_STAF { get; set; }
        public string COD_EVAL_STAF { get; set; }
        public Nullable<int> ID_PERS_STAT { get; set; }
        public Nullable<int> ID_NAME_CHAR { get; set; }
        public Nullable<int> ID_PERS_ENTI_SUPE { get; set; }
        public Nullable<int> ID_PERS_ENTI_UEN { get; set; }
        public Nullable<int> ID_PERS_ENTI_MAGE_GENE { get; set; }
        public Nullable<int> ID_PERS_ENTI_RRHH1 { get; set; }
        public Nullable<int> ID_PERS_ENTI_RRHH2 { get; set; }
        public Nullable<int> ID_PERS_ENTI_CLIE { get; set; }
        public Nullable<int> ID_LOCA { get; set; }
        public Nullable<int> ID_NAME_CHAR_UEN { get; set; }
        public Nullable<int> ID_NAME_CHAR_AREA { get; set; }
    
        public virtual ICollection<DETAIL_EVALUATION_STAFF> DETAIL_EVALUATION_STAFF { get; set; }
        public virtual ICollection<OBJECT_BY_STAFF> OBJECT_BY_STAFF { get; set; }
    }
}

ERPElectrodata/Controllers/EvaluationStaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using ERPElectrodata.Models;
using System.Globalization;
using System.Threading;
using System.Data.Entity;
using System.IO;
using ERPElectrodata.Objects;
using System.Text;

namespace ERPElectrodata.Controllers
{
    public class EvaluationStaffController : Controller
    {
        public CoreEntities dbc = new CoreEntities();
        public EntityEntities dbe = new EntityEntities();
        private CultureInfo cultureInfo = Thread.CurrentThread.CurrentCulture;
        private TextInfo textInfo;
        private int raw = 0;
        
        // GET: /EvaluationStaff/
        public ActionResult Index(int id = 0)
        {
            ViewBag.RETURN = 0;

            int ID_PERS_ENTI = 0;

            if (id == 0)
            {
                ID_PERS_ENTI = Convert.ToInt32(Session["ID_PERS_ENTI"]);
            }
            else
            {
                ID_PERS_ENTI = id;
                ViewBag.RETURN = 1;
            }
            
            try{
                var x = (from ee in dbe.EVALUATION_STAFF
                             join ev in dbe.EVALUATIONs on ee.ID_EVAL equals ev.ID_EVAL
                         where ee.ID_PERS_ENTI == ID_PERS_ENTI && ev.ID_STAT_EVAL == 2
                             select new{
                                 ee.ID_EVAL_STAF,
                                 NAM_EVAL = ev.NAM_EVAL,
                             }).First();

                ViewBag.ID_EVAL_STAF = x.ID_EVAL_STAF;
                ViewBag.NAME_EVAL = x.NAM_EVAL;

                return View();
            }
            catch{
                return Content("Not Evaluation Available");
            }
            
        }

        public ActionResult GPARS(int id)
        {
            textInfo = cultureInfo.TextInfo;

            //int ID_PERS_ENTI = Convert.ToInt32(Session["ID_PERS_ENTI"]);
            // ID_PERS_ENTI = 1069;
            //string username = WebSecurity.CurrentUserName;
            

            var location = (from l in dbc.LOCATIONs.ToList()
                            select new
                            {
                                l.ID_LOCA,
                                NAM_LOCA = textInfo.ToTitleCase(l.NAM_LOCA.ToLower()),

                            }).ToList();

            //var location = dbc.LOCATIONs.ToList() ;

            var query = dbe.EVALUATION_STAFF
                .Where(x => x.ID_EVAL_STAF == id);
                //.Take(1)//.OrderBy(x => x.ID_EVAL_STAF).Select(p => new { p.ID_PERS_ENTI,p.ID_LOCA})
                //.ToList();

            //var query_x = dbe.EVALUATION_STAFF.Single(x => x.ID_EVAL_STAF == id);

            var result2 = (from ee in query
                         join pe in dbe.PERSON_ENTITY on ee.ID_PERS_ENTI equals pe.ID_PERS_ENTI
                          join ce in dbe.CLASS_ENTITY on pe.ID_ENTI2 equals ce.ID_ENTI
                          join ps in dbe.PERSON_STATUS on pe.ID_PERS_STAT equals ps.ID_PERS_STAT
                          join nc in dbe.NAME_CHART on ee.ID_NAME_CHAR equals nc.ID_NAM_CHAR
                          join pes in dbe.PERSON_ENTITY on ee.ID_PERS_ENTI_SUPE equals pes.ID_PERS_ENTI
                          join ces in dbe.CLASS_ENTITY on pes.ID_ENTI2 equals ces.ID_ENTI
                          join peuen in dbe.PERSON_ENTITY on ee.ID_PERS_ENTI_UEN equals peuen.ID_PERS_ENTI
                          join ceuen in dbe.CLASS_ENTITY on peuen.ID_ENTI2 equals ceuen.ID_ENTI
                          join peg in dbe.PERSON_ENTITY on ee.ID_PERS_ENTI_MAGE_GENE equals peg.ID_PERS_ENTI
                          join ceg in dbe.CLASS_ENTITY on peg.ID_ENTI2 equals ceg.ID_ENTI
                         //join loca in location on ee.ID_LOCA equals loca.ID_LOCA
                          join uen in dbe.NAME_CHART on ee.ID_NAME_CHAR_UEN equals uen.ID_NAM_CHAR
                          join area in dbe.NAME_CHART on ee.ID_NAME_CHAR_AREA equals area.ID_NAM_CHAR

                         select new
                             {
                                 EVA_TIME = ee.EVA_TIME,
                                 NUM_EMPL_EVAL = ee.NUM_EMPL_EVAL,
                                 NUM_EMPL_UEN = ee.NUM_EMPL_EVAL_UEN,
                                 NUM_EMPL_AREA = ee.NUM_EMPL_EVAL_AREA,
                                 NAM_EMPL = ce.FIR_NAME+" "+ce.LAS_NAME,
                                 COD_EMPL = ee.COD_EVAL_STAF,
                                 NAM_STAT = ps.NAM_STAT,
                                 JOB_TITL = nc.NAM_CHAR_ENGL,
                                 NAM_SUPER = ces.FIR_NAME + " " + ces.LAS_NAME,
                                 NAM_GER_UEN = ceuen.FIR_NAME + " " + ceuen.LAS_NAME,
                                 NAM_GERE_GENE = ceg.FIR_NAME + " " + ceg.LAS_NAME,
                                 NAM_UEN = uen.NAM_CHAR_ENGL,
                                 NAM_AREA = area.NAM_CHAR_ENGL,
                                 ID_FOTO = pe.ID_FOTO,
                                 FOT_SUPE = pes.ID_FOTO,
                                 FOT_UEN = peuen.ID_FOTO,
                                 FOT_GERE_GENE = peg.ID_FOTO,
                                 USER_ELEC = "",
                                 ID_LOCA = ee.ID_LOCA
                             }).ToList();

            var result = (from l in location
                          join p in result2 on l.ID_LOCA equals p.ID_LOCA
                          select new
                          {
                              EVA_TIME = p.EVA_TIME,
                              NUM_EMPL_EVAL = p.NUM_EMPL_EVAL,
                              NUM_EMPL_UEN = p.NUM_EMPL_UEN,
                              NUM_EMPL_AREA = p.NUM_EMPL_AREA,
                              NAM_EMPL = textInfo.ToTitleCase(p.NAM_EMPL.ToLower()),
                              COD_EMPL = p.COD_EMPL,
                              NAM_STAT = textInfo.ToTitleCase(p.NAM_STAT.ToLower()),
                              JOB_TITL = p.JOB_TITL,
                              NAM_SUPER = textInfo.ToTitleCase(p.NAM_SUPER.ToLower()),
                              NAM_GER_UEN = textInfo.ToTitleCase(p.NAM_GER_UEN.ToLower()),
                              NAM_GERE_GENE = textInfo.ToTitleCase(p.NAM_GERE_GENE.ToLower()),
                              NAM_LOCA = l.NAM_LOCA,
                              NAM_UEN = p.NAM_UEN,
                              NAM_AREA = p.NAM_AREA,
                              ID_FOTO = p.ID_FOTO,
                              FOT_SUPE = p.FOT_SUPE,
                              FOT_UEN = p.FOT_UEN,
                              FOT_GERE_GENE = p.FOT_GERE_GENE,
                              USER_ELEC = "username",//username,
                          });

            return Json(new { Data = result, Count = result.Count() }, JsonRequestBehavior.AllowGet);
        }


        //public ActionResult ObjectBySatff()
        //{
        //    textInfo = cultureInfo.TextInfo;

        //    //-------Estos Valores son lo que debe recibir.-----------

        //    int ID_PERS_ENTI = 10491;
        //    int ID_EVAL = 2;

        //    var query = (from oe in dbe.OBJECT_BY_STAFF.Where(x => x.ID_PERS_ENTI == ID_PERS_ENTI).ToList()
        //                 join o in dbe.OBJETIVES.Where(y => y.ID_EVAL == ID_EVAL) on oe.ID_OBJE equals o.ID_OBJE
        //                 join e in dbe.EVALUATIONs on o.ID_EVAL equals e.ID_EVAL
        //                 join pe in dbe.PERSON_ENTITY on oe.ID_PERS_ENTI equals pe.ID_PERS_ENTI
        //                 join ce in dbe.CLASS_ENTITY on pe.ID_ENTI2 equals ce.ID_ENTI
        //                 select new
        //                 {
        //                     NAM_EVAL = e.NAM_EVAL,
        //                     DAT_STAR = String.Format("{0:d}", e.DAT_START),
        //                     DAT_END = String.Format("{0:d}",  e.DAT_END),
        //                     //NUM_DAYS = (e.DAT_END - e.DAT_START),
        //                     COD_OBJE = oe.COD_OBJE_STAF,
        //                     NAM_OBJE = o.NAM_OBJE,
        //                     NAM_EMPL = textInfo.ToTitleCase((ce.FIR_NAME.ToLower() + " " + ce.LAS_NAME.ToLower() + " " + (ce.MOT_NAME == null ? "" : ce.MOT_NAME).ToLower())),

        //                 });


        //    return Json(new { Data = query, Count = query.Count() }, JsonRequestBehavior.AllowGet);
        //}

        //public ActionResult ListObjectBySatff()
        //{
        //    return View();
        //}

        public ActionResult SatffBySupervisor()
        {
            textInfo = cultureInfo.TextInfo;

            //-------Estos Valores son lo que debe recibir.-----------

            int ID_PERS_ENTI_SUPE = Convert.ToInt32(Session["ID_PERS_ENTI"]);//507;
            // int ID_EVAL = 2;      
          
            var query1 = (from es in dbe.EVALUATION_STAFF.Where(ev=>ev.ID_PERS_ENTI_SUPE==ID_PERS_ENTI_SUPE).ToList()
                         join pe in dbe.PERSON_ENTITY on es.ID_PERS_ENTI equals pe.ID_PERS_ENTI
                         join ce in dbe.CLASS_ENTITY on pe.ID_ENTI2 equals ce.ID_ENTI
                         join pc in dbe.PERSON_CONTRACT on pe.ID_PERS_ENTI equals pc.ID_PERS_ENTI
                         join c in dbe.CHARTs on pc.ID_CHAR equals c.ID_CHAR
                         join nc in dbe.NAME_CHART on c.ID_NAM_CHAR equals nc.ID_NAM_CHAR
                         where pc.VIG_CONT==true
                         where c.VIG_CHAR==true
                         select new
                         {
                             ID_PERS_ENTI=pe.ID_PERS_ENTI,
                             NAM_EMPL = textInfo.ToTitleCase((ce.FIR_NAME.ToLower() + " " + ce.LAS_NAME.ToLower() + " " + (ce.MOT_NAME == null ? "" : ce.MOT_NAME).ToLower())),
                             ID_PHOTO=pe.ID_FOTO,
                             ID_EVAL_STAF=es.ID_EVAL_STAF,

ERPElectrodata/Views/EvaluationStaff/ComplianceObjectivesByStaff.cshtml
@model ERPElectrodata.Models.COMPLIANCE_BY_OBJECTIVES

@{
    Layout = null;
}

<div id="contobjectives" style="float:left; width:100%;">
    <div class="titleForm">
        <div style="display:inline-block; width:100%; height:20px;">
            <div class="title" style="float:left; width:30%;">Comments</div>
            <div style="padding-top:3px; padding-right:1%; float:right; width:64%; text-transform:capitalize; text-align:right;" id="NamObjective"></div>
        </div>
    </div>
    <div class="bodyForm">
        <div class="inBodyForm">
            @*<div id="divnewcomment" style="float:right; padding-right:15px;"><a onclick="LoadNewComment(this)" href="#">New Comment</a></div>*@
            <div style="clear:both"></div>

  @* -------------------------------------FORMULARIO--------------------------------- *@

            <div style="padding:10px 10px 0px 15px;">
                @using (Html.BeginForm("SaveComplianceObjectivesByStaff", "EvaluationStaff", FormMethod.Post, new { enctype = "multipart/form-data", id = "FrmDetailIncident", target = "upload_target" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <div style="width:100%;">
                        <div style="width:100%;">
                            
                            <div id="valuation"></div>
                            
                            <div style="width: 99%; float: left; margin-top: 7px;">
                                <div class="editor-label">
                                    Comment
                                </div>
                                <div class="editor-field" style="margin-top: 2px;">
                                    @Html.TextAreaFor(model => model.COM_COMP_OBJE, new { rows = "20" })
                                    @Html.ValidationMessageFor(model => model.COM_COMP_OBJE)
                                    <input type="hidden" value="@ViewBag.ID_OBJE_STAF" name="ID_OBJE_STAF" />
                                    <input type="hidden" value="@ViewBag.ID_PERS_ENTI_OBJE" name="ID_PERS_ENTI_OBJE" />

                                </div>
                            </div>

                            <div style="clear:both;"></div>

                            <div style="height:10px;"></div>
                            <div style="margin:0px 15px 0px 0px; height:25px; border:0px solid black;">
                                <div style="width: 96%; float:left; padding: 0px 0px 0 15px; ">
                                    <input name="files" id="files" type="file" />
                                </div>

                                <div style="float:right;padding:10px 0px 0px 0px; ">
                                    <button id="submit" class="k-button">Create</button>
                                </div>
                            </div>

                            <iframe id="upload_target" name="upload_target" src="" style="width:0px; height:0px; visibility:hidden;"></iframe>
                            <div style="clear:both; padding-top:10px;"></div>
                        </div>
                    </div>
                }
            </div>
@* --------------------------------------------------------------------- *@
            <div id="commentcompliace"></div>

        </div>
    </div>
</div>


<a style="text-decoration:none; text-align:left; z-index:10;"></a>

<script type="text/javascript">

    $(document).ready(function () {

        $("#submit").click(function () {
            var body = "<div style='padding:5px 10px 10px 5px;'>Please wait saving information</div>";      

            winPopUpModalLoad('Saving information', body, 300, 130);
        });

        $("#files").kendoUpload({
            localization: {
                select: "@ResourceLanguaje.Resource.Attach"
            }
        });

        if ("@ViewBag.banderaval"==1)
        {
            $("#valuation").append("<div>Valuation</div><div style='margin-top: 2px;'><input id='percentage' value='@ViewBag.val' name='VAL_COMP_OBJE' /></div>");

            $("#percentage").kendoNumericTextBox({
            format: "p0",
            min: 0,
            max: 1,
            step: 0.01

            });
        }

        $("#COM_COMP_OBJE").kendoEditor({
             encoded: false
        })
               
            $.ajax({
                url: "/EvaluationStaff/CommentsCompliance/?ID_OBJE_STAF="+@ViewBag.ID_OBJE_STAF+"&var="+Math.random(),
                data: "var=" + Math.random(),
                type: "GET",
                dataType: "json",
                success: function (source) {
                    jsonx = source;
                    ListComments();

                },
                error: function (source) {
                    alert("Error Carga Json");
                }
            });
            function ListComments() {
                $.each(jsonx['Data'], function (index, value) {

                    $("#commentcompliace").append('<div class="detailsSummary">' +
                         '<div id="detSummary">' +
                             '<div class="container">' +
                                 '<div class="userData">' +
                                     '<div class="asignedImage"><a href="#"><img src="/Content/Fotos/' + value['PHOTO'] + '.jpg"/></a></div>' +
                                 '</div>' +
                                 '<div class="messageData">' +
                                     '<div class="messageArrow"></div>' +
                                         '<div class ="messageBoxDet">' +
                                             '<div class ="msgBoxDetUser">' +
                                                 value['NAM_STAFF'] +
                                             '</div>' +
                                             '<div class ="msgBoxDetCreate">' +
                                                 value['CREATE'] +
                                             '</div>' +
                                         '</div>' +

                                     '<div class="msgBoxBody">' +
                                          value['COMMENT'] +
                                     '</div>' +

                                     '<div class ="dadjuntos">' +
                                         value['ADJ'] +
                                     '</div>' +

                                    '</div>' +//message Data
                             '</div>' +
                         '</div>' +
                     '</div>');                   
                             
                   
                    //x = value['ID_EVAL_STAF'];
                });


                var nameobje = jsonx.NAM_OBJE;

                if (nameobje.length <= 60) {
                    $("#NamObjective").html(nameobje);
                }
                else {
                    var res = nameobje.substr(0, 58);
                    $("#NamObjective").html(res);
                    $("#NamObjective").append("<a class='zoom' href='#' style='z-index:10; overflow: scroll; text-decoration:none; color:white; text-align:left;'><span>" + nameobje + "</span>...</a>");
                }
            }

        });
    

    function uploadDone(conf) {
        closeWinModalPopUpLoad();
        if (conf == 'OK') {
            var title = '@ResourceLanguaje.Resource.InformationSaved ';
            var body = "<div style='padding:0px 0px 20px 0px;'>" +
                            "<div style='padding:5px 0px 10px 0px;'>Your information has been successfully saved</div>" +
                            "<div style='float:right; padding:15px 10px 0px 6px; font-size:0.9em;'>" +
                            "<button id='btnContinues' class='k-button'>Continue</button>" +
                            "</div></div>";

            winPopUpModal(title, body, 300, 130);

            $("#closebtnmodal").click(function () {
                location.reload(true);

            });

            $("#btnContinues").click(function () {
                location.reload(true);
            });
        }
        else {
            var title = '@ResourceLanguaje.Resource.InformationMissing';
            var body = "<div style='padding:0px 0px 20px 0px;'>" +
                          "<div style='padding:10px 0px 10px 0px;'>You must introduce your comment</div>" +
                          "<div style='float:right; padding:15px 10px 0px 6px; font-size:0.9em;'>" +
                          "<button id='btnContinuee' class='k-button'>Continue</button>" +
                          "</div></div>";

            winPopUpModal(title, body, 300, 130);

            $("#btnContinuee").click(function () {
                $("#dlg").hide('200', "swing", function () {
                    $("#bkg").fadeOut("300");
                });
            });
        }
    }


    </script>

ERPElectrodata/Views/EvaluationStaff/ListStaffBySupervisor.cshtml
@{
    ViewBag.Title = "List Staff By Supervisor";
    Layout = null;
}

@*<div style="width:50%;">*@

    <div class="titleForm">
        <div style="display:inline-block; width:100%; height:20px;">
            <div class="title" style="float:left; width:30%;">
                <div style="float:left;" onclick="ReturnEvaluation(this)">
                    <img style="margin-top:-1px;" src="~/Content/Images/arrow_return.png" />
                </div>&nbsp;Staff
            </div>
            <div style="padding-top:3px; padding-right:1%; float:right; width:64%; text-transform:capitalize; text-align:right;" id="Staff_eval"></div>
        </div>
    </div>
    
    <div class="bodyForm">

        <div class="inBodyForm">
            <div style="height:10px;">&nbsp;</div>
            <div id="divnamestaff" style="text-align:center;">
            </div>
        </div>
    </div>

@*</div>*@



        @*<div class='contstaff' style="width:50%;">
            <div style='width: 50px; float:left;'><div style='width:100%;'><img class='photo' src='http://itms.electrodata.com.pe/Content/Fotos/10491.jpg' /></div></div>

            <div style='width: 300px; float: left; text-align: left; padding: 3px 10px 0px 10px; border: 0px solid blue;'>
                <div style='color: #3e4752; font-weight: 800; '>Luis Sempertegui Cotrina</div>
                <div style='padding-top: 10px; font-size: 12px; color: #4c5356; font-family: sans-serif; '>Development Engineer | 50% | <a style="color: #10c4b2;  cursor:pointer;"> 5 Comments</a></div>
            </div>         

            <div style='clear:both;'></div>
        </div><br>*@
    
<span></span>
<a onclick="DashStaff()"></a>
<script type="text/javascript">
    function DashStaff(id) {
        $('#myModalLoading').modal('show');
        $("#divContent").empty();
        $("#divContent").load("/EvaluationStaff/Index/" + id + "?var=" + Math.random());
    };

    $(document).ready(function () {
        $.ajax({
            url: "/EvaluationStaff/SatffBySupervisor/",
            data: "var=" + Math.random(),
            type: "GET",
            dataType: "json",
            success: function (source) {
                jsonx = source;
                ListStaff();
            },
            error: function (source) {
                alert("Error Carga Json");
            }
        });

        function ListStaff() {
            $.each(jsonx['Data'], function (index, value) {
                $("#divnamestaff").append("<a onclick='DashStaff(" + value['ID_PERS_ENTI'] + ")'  style='text-decoration:none; cursor:pointer;'>" +
                 "<div class='contstaff'>"+
                   "<div style='width: 50px; float:left;'><div style='width:100%;'>" +
                     "<img class='photo' src='http://itms.electrodata.com.pe/Content/Fotos/" + value['ID_PHOTO'] + ".jpg'/>"+
                     "</div>"+
                   "</div>" +

                 "<div style ='float: left; text-align: left; padding:3px 10px 0px 10px;' >" +
                    "<div style='color: #3e4752;font-weight:800;'>" + value['NAM_EMPL'] + "</div>" +
                     "<div style='padding-top: 10px; font-size: 12px; font-family: 'sans-serif'; '>" + value['NAM_CHAR'] + " <span style='color:#4c5356'>|</span> 50% <span style='color:#4c5356'>|</span> <span style='color: #10c4b2;'> " + value['Comments'] + " Comments</span></div>" +
                  "</div>"+                  
                 
                 "<div style='clear:both;'></div>" +
                 "</div>" +
                 "<br>" +
                "</a>");
            });
        }       

    })
    
</script>

ERPElectrodata/Views/EvaluationStaff/NewComment.cshtml
@model ERPElectrodata.Models.DETAIL_EVALUATION_STAFF

@{
     Layout = null;
}



@*<h2>New Comment</h2>*@

<div style="width:100%;">
    @using (Html.BeginForm("SaveCommentEvaluation", "DetailEvaluationStaff", FormMethod.Post, new { enctype = "multipart/form-data", id = "FrmDetailEvaluation", target = "upload_target" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="modal-body">
            <div class="divFondoUno">
                <div style="width:100%;float:left">
                    <div class="editor-label">
                        Comments
                    </div>
                    <div class="editor-field">
                        @Html.TextAreaFor(model => model.COM_DETA_EVAL_STAF, new { rows = "20" })
                        @Html.ValidationMessageFor(model => model.COM_DETA_EVAL_STAF)
                        <input type="hidden" value="@ViewBag.idevalstaf" name="ID_EVAL_STAF" />
                    </div>
                </div>
            </div>
         </div>
        
        <div class="modal-footer">
            <button type="button" class="k-button" data-dismiss="modal">Close</button>
            <button id="submit" class="k-button">Create</button>
        </div>
        @*<div style="margin:0px 15px 0px 0px; height:25px; border:0px solid black;">
            <div style="float:right;padding:10px 0px 0px 0px; ">
                <button id="submit" class="k-button">Create</button>
            </div>
        </div>*@
        
        <iframe id="upload_target" name="upload_target" src="" style="width:0px; height:0px; visibility:hidden;"></iframe>
        <div style="clear:both; padding-top:10px;"></div>
    }
</div>



<script type="text/javascript">

    $(document).ready(function () {

        //$("#submit").click(function () {
        //    winPopUpModalLoad('Saving information', 'Please wait saving information', 300, 130);
        //});

        $("#COM_DETA_EVAL_STAF").kendoEditor({
            tools: [
                "bold",
                "italic",
                "underline",
                "strikethrough",
                "foreColor",
                "backColor",
                "justifyLeft",
                "justifyCenter",
                "justifyRight",
                "justifyFull",
                "insertUnorderedList",
                "insertOrderedList",
                "indent",
                "outdent",
                "createLink",
                "unlink",
                "subscript",
                "superscript"
            ], encoded: false
        });
    })

    function uploadDone(conf, msg) {

        //closeWinModalPopUpLoad();

        if (conf == 'OK') {

            //closeWinModalPopUp();
            $('#modNewComm').modal('hide');
            //
            $('#modNewComm').on('hidden.bs.modal', function (e) {
                $("#pnlEvaluationWork").empty();
                $("#pnlEvaluationWork").load("/DetailEvaluationStaff/Index/" + "@ViewBag.idevalstaf" + "?_" + Math.random());
            })
            @*setTimeout(function () {

                var title = '@ResourceLanguaje.Resource.InformationSaved ';
                var body = "<div style='padding:0px 0px 20px 0px;'>" +
                            "<div style='padding:10px 0px 10px 0px;'>Your comment has been successfully saved</div>" +
                            "<div style='float:right; padding:15px 10px 0px 6px; font-size:0.9em;'>" +
                            "<button id='btnContinues' class='k-button'>Continue</button>" +
                            "</div></div>";

                winPopUpModal(title, body, 300, 130);

                $("#btnContinues").click(function () {
                    location.reload(true);
                });

            }, 1000);*@

            // closeWinModalPopUpLoad();
        }
        else {
            $('#modNewComm').modal('hide');
            @*closeWinModalPopUp();
            setTimeout(function () {
                var title = '@ResourceLanguaje.Resource.InformationMissing';
                var body = "<div style='padding:0px 0px 20px 0px;'>" +
                            "<div style='padding:10px 0px 10px 0px;'>You have not made ​​any comment</div>" +
                            "<div style='float:right; padding:15px 10px 0px 6px; font-size:0.9em;'>" +
                            "<button id='btnContinues' class='k-button'>Continue</button>" +
                            "</div></div>";

                winPopUpModal(title, body, 300, 130);

                $("#btnContinues").click(function () {
                    //location.reload(true);
                    closeWinModalPopUp();
                });


            }, 1000);

            closeWinModalPopUpLoad();*@
        }
    }
</script>