ERPElectrodata/Models/DETAILS_TICKET.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILS_TICKET
    {
        public DETAILS_TICKET()
        {
            this.ATTACHED = new HashSet<ATTACHED>();
        }
    
        public int ID_DETA_TICK { get; set; }
        public Nullable<int> ID_TICK { get; set; }
        public Nullable<int> ID_STAT { get; set; }
        public Nullable<int> ID_CLIE { get; set; }
        public Nullable<int> ID_QUEU { get; set; }
        public Nullable<int> ID_TICK_PARENT { get; set; }
        public Nullable<int> ID_TYPE_DETA_TICK { get; set; }
        public string COM_DETA_TICK { get; set; }
        public Nullable<System.DateTime> FEC_SCHE { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CREATE_DETA_INCI { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> MINUTES { get; set; }
        public Nullable<int> IND { get; set; }
        public Nullable<int> ID_STAT_SALE_OPP { get; set; }
        public Nullable<decimal> AMM_SALE_OPP { get; set; }
        public Nullable<decimal> PRO_SALE_OPP { get; set; }
        public Nullable<System.DateTime> FROM_TIME { get; set; }
        public Nullable<System.DateTime> TO_TIME { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public Nullable<System.DateTime> CREATED_MAIL { get; set; }
        public Nullable<System.DateTime> GET_DATE { get; set; }
        public Nullable<int> ID_ENTI_CREATED { get; set; }
        public Nullable<int> ID_ENTI_TRAN { get; set; }
        public Nullable<int> ID_REAS_SCHE { get; set; }
        public Nullable<System.DateTime> FEC_END_REAL { get; set; }
        public Nullable<bool> EsperaPorCliente { get; set; }
        public string Titulo { get; set; }
        public string DescripcionProblema { get; set; }
        public string SolucionAplicada { get; set; }
        public string Impactonegocio { get; set; }
        public string SolucionTemporal { get; set; }
        public string SolucionDefinitiva { get; set; }
        public Nullable<bool> Causa { get; set; }
        public string Porque2 { get; set; }
        public string Porque3 { get; set; }
        public string Porque4 { get; set; }
        public string Porque5 { get; set; }
        public Nullable<bool> PortalComent { get; set; }
        public Nullable<int> IdTipoResolucion { get; set; }
        public Nullable<int> IdRazon { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdMotivoEstado { get; set; }
        public string ImpactoServicio { get; set; }
        public Nullable<int> MinutosBolsaHoras { get; set; }
    
        public virtual ICollection<ATTACHED> ATTACHED { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual TYPE_DETAILS_TICKET TYPE_DETAILS_TICKET { get; set; }
    }
}

ERPElectrodata/Controllers/DetailsTicketController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERPElectrodata.Models;
using System.IO;
using System.Configuration;
using ERPElectrodata.Objects;
using System.Threading;
using System.Globalization;
using ERPElectrodata.Object;
using ERPElectrodata.Object.Ticket;
using System.Web.Security;
using Electrodata.ERPElectrodata.Domain.Services.LeccionAprendidaService;
using Electrodata.ERPElectrodata.Infra.Reposotories.LeccionAprendidaRepositorie;
using Electrodata.ERPElectrodata.Domain.Entities.Enum;
using System.Text;
using ERPElectrodata.Models.Enum;
using RestSharp;
using System.Threading.Tasks;

namespace ERPElectrodata.Controllers
{
    [Authorize]
    public class DetailsTicketController : Controller
    {

        public LeccionAprendidaService _srvLeccionAprendidaService = new LeccionAprendidaService(new LeccionAprendidaRepositorie());
        int result = (int)Tipo_Peracion.OPERATION_ERROR;
        private CoreEntities db = new CoreEntities();
        public EntityEntities dbe = new EntityEntities();
        private PointTicket pt = new PointTicket();
        private CultureInfo cultureInfo = Thread.CurrentThread.CurrentCulture;
        private TextInfo textInfo;
        public TicketIR tir = new TicketIR();
        /*variables globales gestión del conocimiento*/
        int nivel1 = 0, nivel2 = 0, nivel3 = 0, nivel4 = 0, idTema = 0;
        string nameNivel1 = string.Empty, nameNivel2 = string.Empty, nameNivel3 = string.Empty, nameNivel4 = string.Empty, nameTema = string.Empty;
        bool Flagproblema;
        /*Fin*/

        //
        // GET: /DetailsTicket/ListByIdTick


        #region "gestión Problemas"
        public JsonResult UpdateDetailsTicket(int idTicket = 0)
        {
            var data = db.ComLeccionAprendidas.Where(x => x.ID_TICKET == idTicket && x.SolucionDefinitiva == "").FirstOrDefault();
            Electrodata.ERPElectrodata.Domain.Entities.ComLeccionAprendida objLeccionAprendida = new Electrodata.ERPElectrodata.Domain.Entities.ComLeccionAprendida();

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion






        public ActionResult UpdateDatesDetailsTicket(int id)
        {
            DETAILS_TICKET query = db.DETAILS_TICKET.Single(x => x.ID_DETA_TICK == id);
            ViewBag.COM_DETA_TICK_EDIT = query.COM_DETA_TICK;
            ViewBag.FEC_SCHE_EDIT = query.FEC_SCHE;
            ViewBag.ID_STAT_EDIT = query.ID_STAT;
            ViewBag.ID_TYPE_DETA_TICK_EDIT = query.ID_TYPE_DETA_TICK;
            ViewBag.CREATE_DETA_INCI_EDIT = query.CREATE_DETA_INCI;
            ViewBag.UploadFile = "M1CT" + Convert.ToString(DateTime.Now.Ticks);
            ViewBag.PortalComent = Convert.ToBoolean(query.PortalComent);
            ViewBag.FechaInicio = query.FROM_TIME;
            ViewBag.FechaFin = query.TO_TIME;
            ViewBag.MinEfectivos = query.MinutosBolsaHoras;
            
            if (Convert.ToInt32(Session["ID_ACCO"]) == 3 && query.ID_STAT == 4)
            {
                ViewBag.FEC_END_REAL_EDIT = query.FEC_END_REAL;
            }
            ViewBag.Habilitado = Convert.ToInt16(Session["SUPERVISOR_SERVICEDESK"]);
            return View(query);
        }

        [Authorize]
        [HttpPost, ValidateInput(false)]
        public ActionResult UpdateDatesDetailsTicket(IEnumerable<HttpPostedFileBase> archivos, DETAILS_TICKET detatick)
        {
            try
            {
                int ID_DETA_TICK = Convert.ToInt32(detatick.ID_DETA_TICK);
                string COM_DETA_TICK = Convert.ToString(Request.Params["COM_DETA_TICK_EDIT"]);
                string STR_STAT_EDIT = Convert.ToString(Request.Params["ID_STAT_EDIT"]);
                int ID_TYPE_DETA_TICK = Convert.ToInt32(Request.Params["ID_TYPE_DETA_TICK_EDIT"]);
                DateTime CREATE_DETA_INCI = Convert.ToDateTime(Request.Params["CREATE_DETA_INCI_EDIT"]);
                int SECOND_CREATE_DETA_INCI = Convert.ToInt32(Request.Params["SECOND_CREATE_DETA_INCI_EDIT"]);
                int MILLISECOND_CREATE_DETA_INCI = Convert.ToInt32(Request.Params["MILLISECOND_CREATE_DETA_INCI_EDIT"]);
                bool PortalComent = Convert.ToBoolean(detatick.PortalComent);
                int ID_TICK = Convert.ToInt32(detatick.ID_TICK);
                int MinutosBolsa = Convert.ToInt32(Request.Params["MinEfectivos"]);
                string KEY_ATTA = null;
                try
                {
                    KEY_ATTA = Convert.ToString(Request.Form["KEY_ATTA"]);

                }
                catch
                {

                }

                CREATE_DETA_INCI = CREATE_DETA_INCI.AddSeconds(SECOND_CREATE_DETA_INCI).AddMilliseconds(MILLISECOND_CREATE_DETA_INCI);

                DETAILS_TICKET query = db.DETAILS_TICKET.Single(x => x.ID_DETA_TICK == ID_DETA_TICK);

                string FEC_REAL = Convert.ToString(Request.Params["FEC_END_REAL_EDIT"]);
                DateTime FEC_END_REAL;
                if (!string.IsNullOrEmpty(FEC_REAL))
                {
                    FEC_END_REAL = Convert.ToDateTime(Request.Params["FEC_END_REAL_EDIT"]);
                    query.FEC_END_REAL = FEC_END_REAL;
                }

                int ID_STAT_EDIT = 0;
                if (!string.IsNullOrEmpty(STR_STAT_EDIT))
                {
                    ID_STAT_EDIT = Convert.ToInt32(STR_STAT_EDIT);
                }

                if (String.IsNullOrEmpty(COM_DETA_TICK.Trim()))
                {
                    return Content("<script type='text/javascript'> function init() {" +
                "if(top.uploadDoneEdit) top.uploadDoneEdit('ERROR','Ingrese un Comentario');}window.onload=init;</script>");
                }
                try
                {
                    DateTime FechaInicio = Convert.ToDateTime(Request.Params["FechaInicio"]);
                    DateTime fechaFin = Convert.ToDateTime(Request.Params["FechaFin"]);
                    ACTIVITY_LOG queryAct = dbe.ACTIVITY_LOG.Single(x => x.DETAILS_TICKETS == ID_DETA_TICK);
                    queryAct.DATE_INIC = FechaInicio;
                    queryAct.DATE_END = fechaFin;
                    queryAct.TIEMPO_ACT = (int)(Convert.ToDateTime(fechaFin).Subtract(Convert.ToDateTime(FechaInicio))).TotalSeconds;
                    dbe.Entry(queryAct).State = EntityState.Modified;
                    dbe.SaveChanges();
                }
                catch
                {
                }
                if (query.UserId == 34)
                {
                    query.COM_DETA_TICK = COM_DETA_TICK;
                    query.CREATE_DETA_INCI = CREATE_DETA_INCI;
                    query.PortalComent = PortalComent;
                }
                else
                {
                    query.COM_DETA_TICK = COM_DETA_TICK;
                    query.CREATE_DETA_INCI = CREATE_DETA_INCI;
                    query.PortalComent = PortalComent;
                    DateTime FechaInicio = Convert.ToDateTime(Request.Params["FechaInicio"]);
                    DateTime fechaFin = Convert.ToDateTime(Request.Params["FechaFin"]);
                    query.FROM_TIME = FechaInicio;
                    query.TO_TIME = fechaFin;
                }

                if (ID_STAT_EDIT == 5 && ID_TYPE_DETA_TICK == 3)
                {
                    DateTime FEC_SCHE = Convert.ToDateTime(Request.Params["FEC_SCHE_EDIT"]);
                    int SECOND_FEC_SCHE = Convert.ToInt32(Request.Params["SECOND_FEC_SCHE_EDIT"]);
                    int MILLISECOND_FEC_SCHE = Convert.ToInt32(Request.Params["MILLISECOND_FEC_SCHE_EDIT"]);
                    FEC_SCHE = FEC_SCHE.AddSeconds(SECOND_FEC_SCHE).AddMilliseconds(MILLISECOND_FEC_SCHE);

                    query.FEC_SCHE = FEC_SCHE;
                }

                TICKET ticket = db.TICKETs.Where(x=> x.ID_TICK == query.ID_TICK).FirstOrDefault();
                ticket.MODIFIED_TICK = DateTime.Now;
                ticket.MinutosEfectivos = (ticket.MinutosEfectivos - query.MinutosBolsaHoras) + MinutosBolsa;

                query.MinutosBolsaHoras = MinutosBolsa;

                db.Entry(query).State = EntityState.Modified;
                db.SaveChanges();
                if (KEY_ATTA != null)
                {
                    var Attachs = db.ATTACHEDs.Where(x => x.KEY_ATTA == KEY_ATTA)
                        .Where(x => x.ID_INCI == null).ToList();
                    if (Attachs.Count() > 0)
                    {
                        foreach (ATTACHED attach in Attachs)
                        {
                            try
                            {
                                var EObj = db.ATTACHEDs.Single(x => x.ID_ATTA == attach.ID_ATTA);
                                EObj.ID_DETA_INCI = query.ID_DETA_TICK;
                                db.Entry(EObj).State = EntityState.Modified;
                                db.SaveChanges();
                                db.Entry(EObj).State = EntityState.Detached;
                            }
                            catch
                            {

                            }

                        }
                    }
                }

                if (ID_TYPE_DETA_TICK == 3)
                {
                    db.UPDATE_MINUTES_TICKET(ID_TICK);

                }


                return Content("<script type='text/javascript'> function init() {" +
                "if(top.uploadDoneEditDeta) top.uploadDoneEditDeta('OK','La información ha sido actualizada.');}window.onload=init;</script>");
            }
            catch
            {
                return Content("<script type='text/javascript'> function init() {" +
                "if(top.uploadDoneEditDeta) top.uploadDoneEditDeta('ERROR','Contacte al Administrador');}window.onload=init;</script>");

            }
        }

        public ActionResult ListByIdTick(int id)
        {

ERPElectrodata/Views/DetailsTicket/AdjuntarArchivosComentario.cshtml
@{
    ViewBag.Title = "AdjuntarArchivosComentario";
    Layout = null;
}

<div class="form-row">
    <div class="col-md-6">
        <div class="form-group">
            <label id="lblTipoDocumento" for="lblTipoDocumento">
                Tipo de Documento
            </label>
            @Html.TextBox("ArrayFile")
        </div>
    </div>

</div>

<div class="form-row">
        <div class="col-md-12">
            <div class="position-relative form-group">
                <input name="files" id="files" type="file" />
            </div>
        </div>
    </div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#files").kendoUpload({
            localization: {
                select: "Adjuntar"
            },
            upload: function (e) {
                e.data = {
                    ID_TYPE_DOCU_ATTA: $("#ArrayFile").val(),
                    KEY_ATTA: $("#KEY_ATTA").val()
                };
            },
            remove: function (e) {
                e.data = {
                    KEY_ATTA: $("#KEY_ATTA").val()
                };
            },
            async: {
                saveUrl: "/Attach/SaveDetailTicket",
                removeUrl: "/Attach/RemoveDetailTicket"
            }
        });

        var ArrayFile = $("#ArrayFile").kendoComboBox({
            dataTextField: "NAM_TYPE_DOCU_ATTA",
            dataValueField: "ID_TYPE_DOCU_ATTA",
            filter: "contains",
            index: 1,
            autoBind: true,
            delay: 500,
            minLength: 0,
            suggest: true,
            dataSource: {
                schema: {
                    data: "Data",
                    total: "Total"
                },
                transport: {
                    read: "/TypeDocumentModule/ListByModule/1?var=" + Math.random()
                }
            }
        }).data("kendoComboBox");
    });
</script>

ERPElectrodata/Views/DetailsTicket/EditSummary.cshtml
@model ERPElectrodata.Models.DETAILS_TICKET

@{
    Layout = null;
}

@using (Html.BeginForm("EditSummary", "DetailsTicket", FormMethod.Post, new { enctype = "multipart/form-data", id = "FrmEditDetailsTicket", target = "upload_target" }))
{
    <div class="modal-body">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID_DETA_TICK)
        <div class="editor-label">
            Comentario
        </div>
        <div class="editor-field">
            @*@Html.TextAreaFor(model => model.COM_DETA_TICK, new { id = "COM_DETA_TICK_E", name = "COM_DETA_TICK_E" })*@
            <textarea name="COM_DETA_TICK_E" id="COM_DETA_TICK_E">@ViewBag.COM_DETA_TICK</textarea>
        </div>
    </div>

    <div class="modal-footer">
        @*<button onclick="Save()" type="button" class="k-button" >Save</button>*@
        <button id="submit" class="k-button">Save</button>
    </div>
}

<iframe id="upload_target" name="upload_target" src="" class="frameHidden"></iframe>

<script type="text/javascript">
    $(document).ready(function () {
        $("#COM_DETA_TICK_E").kendoEditor({
            encoded: false
        });
    });

    function uploadDoneEditDeta(val, msg) {
        //alert('sd');
        if (val == "OK") {
            $('#EditCommentModal').modal('hide');
            alert(msg);
            location.reload();
        }
        else
        {
            $('#EditCommentModal').modal('hide');
            alert(msg);
        }
    }
</script>

ERPElectrodata/Views/DetailsTicket/UpdateDatesDetailsTicket.cshtml
@model ERPElectrodata.Models.DETAILS_TICKET

@{
    Layout = null;
}
<link href="~/Content/themes/plugin/iCheck/square/blue.css" rel="stylesheet" />
<script src="~/Content/themes/plugin/iCheck/icheck.js"></script>
<script>
    $(document).ready(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
</script>

@using (Html.BeginForm("UpdateDatesDetailsTicket", "DetailsTicket", FormMethod.Post, new { enctype = "multipart/form-data", id = "FrmEditDetailsTicket", target = "upload_target" }))
{

<div class="main-card card">
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ID_DETA_TICK)
    @Html.HiddenFor(model => model.ID_TICK)
    <input type="hidden" value="@ViewBag.UploadFile" name="KEY_ATTA" readonly="readonly" />
    <input type="hidden" name="ID_STAT_EDIT" value="@ViewBag.ID_STAT_EDIT" />
    <input type="hidden" name="ID_TYPE_DETA_TICK_EDIT" value="@ViewBag.ID_TYPE_DETA_TICK_EDIT" />

    <input type="hidden" id="SECOND_CREATE_DETA_INCI_EDIT" name="SECOND_CREATE_DETA_INCI_EDIT" />
    <input type="hidden" id="MILLISECOND_CREATE_DETA_INCI_EDIT" name="MILLISECOND_CREATE_DETA_INCI_EDIT" />
    <input type="hidden" id="SECOND_FEC_SCHE_EDIT" name="SECOND_FEC_SCHE_EDIT" />
    <input type="hidden" id="MILLISECOND_FEC_SCHE_EDIT" name="MILLISECOND_FEC_SCHE_EDIT" />
    <div class="card-body">
        <div class="form-row">
            <div class="col-md-6">
                Creado
                <input id="CREATE_DETA_INCI_EDIT" name="CREATE_DETA_INCI_EDIT" />
            </div>

            <div class="col-md-6" id="divfechaschedule" hidden>
                Fecha Programada
                <input id="FEC_SCHE_EDIT" name="FEC_SCHE_EDIT" />

            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="col-md-6">
                Fecha inicio
                <input id="FechaInicio" name="FechaInicio" />
            </div>
            <div class="col-md-6">
                Fecha fin
                <input id="FechaFin" name="FechaFin" />
            </div>
        </div>
    </div>
    @{
        if (Convert.ToInt32(Session["ID_ACCO"].ToString()) == 4 && ViewBag.MinEfectivos > 0)
        {
            <div class="card-body">
                <div class="form-row">
                    <div class="col-md-6">
                        Minutos Efectivos
                        <input type="number" id="MinEfectivos" name="MinEfectivos" value="@ViewBag.MinEfectivos"/>
                    </div>
                </div>
            </div>
        }
    }
    @{
        if (Convert.ToInt32(Session["ID_ACCO"].ToString()) == 3 && Model.ID_STAT == 4)
        {
            <div class="card-body">
                <div class="form-row">
                    <div class="col-md-6">
                        Fecha Fin Real
                        <input id="FEC_END_REAL_EDIT" name="FEC_END_REAL_EDIT" />
                    </div>

                </div>
            </div>
        }
    }
    <div class="card-body">
        <div class="form-row">
            <div class="col-md-12">
                Comentario
                <textarea name="COM_DETA_TICK_EDIT" id="COM_DETA_TICK_EDIT">@ViewBag.COM_DETA_TICK_EDIT</textarea>
            </div>

        </div>
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="col-md-12" style="text-align:center">
                ¿Ver en el Portal?
                @Html.CheckBox("PortalComent", "@ViewBag.PortalComent")
                @Html.ValidationMessageFor(model => model.PortalComent)
            </div>

        </div>
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="col-md-12">
                <input name="archivos" id="archivos" type="file" />
            </div>

        </div>
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="col-md-9">
                &nbsp;
            </div>
            <div class="col-md-3">
                <button id="submit" class="btn btn-warning btn-block">Guardar</button>
            </div>
        </div>
    </div>
</div>
   

   
}

<iframe id="upload_target" name="upload_target" src="" class="frameHidden" hidden></iframe>

<script type="text/javascript">
    $(document).ready(function () {

        $("#archivos").kendoUpload({
            localization: {
                select: "Adjuntar"
            },
            upload: function (e) {
                e.data = {
                    ID_TYPE_DOCU_ATTA: $("#ArrayFile").val(),
                    KEY_ATTA: '@ViewBag.UploadFile'
                };
            },
            remove: function (e) {
                e.data = {
                    KEY_ATTA: '@ViewBag.UploadFile'
                };
            },
            async: {
                saveUrl: "/Attach/EditSaveAttachTicket",
                removeUrl: "/Attach/EditRemoveAsyncAttachTicket"
            }
        });
        $("#COM_DETA_TICK_EDIT").kendoEditor({
            encoded: false,
            paste: OnPaste
        });
        $("#FechaInicio").kendoDateTimePicker();
        var fI = new Date('@ViewBag.FechaInicio');
        var FechaInicio = $("#FechaInicio").data("kendoDateTimePicker");
        FechaInicio.value(new Date(fI.getFullYear(), fI.getMonth(), fI.getDate(), fI.getHours(), fI.getMinutes(), fI.getSeconds(), fI.getMilliseconds()));
        
        $("#FechaFin").kendoDateTimePicker();
        var fF = new Date('@ViewBag.FechaFin');
        var FechaFin = $("#FechaFin").data("kendoDateTimePicker");
        FechaFin.value(new Date(fF.getFullYear(), fF.getMonth(), fF.getDate(), fF.getHours(), fF.getMinutes(), fF.getSeconds(), fF.getMilliseconds()));

        $("#CREATE_DETA_INCI_EDIT").kendoDateTimePicker();
        var CREATE_DETA_INCI_EDIT = $("#CREATE_DETA_INCI_EDIT").data("kendoDateTimePicker");
        var f = new Date('@ViewBag.CREATE_DETA_INCI_EDIT');
        CREATE_DETA_INCI_EDIT.value(new Date(f.getFullYear(), f.getMonth(), f.getDate(), f.getHours(), f.getMinutes(), f.getSeconds(), f.getMilliseconds()));

        $("#SECOND_CREATE_DETA_INCI_EDIT").val(f.getSeconds());
        $("#MILLISECOND_CREATE_DETA_INCI_EDIT").val(f.getMilliseconds());

        if (parseInt('@ViewBag.ID_STAT_EDIT') == 5 && parseInt('@ViewBag.ID_TYPE_DETA_TICK_EDIT') == 3) {
            //$("#divfechaschedule").removeClass("divHide");
            $("#divfechaschedule").removeAttr("hidden");
            //$("#divfechaschedule").attr("hidden", true);
            $("#FEC_SCHE_EDIT").kendoDateTimePicker();

            var d = new Date('@ViewBag.FEC_SCHE_EDIT');
            var FEC_SCHE_EDIT = $("#FEC_SCHE_EDIT").data("kendoDateTimePicker");
            FEC_SCHE_EDIT.value(new Date(d.getFullYear(), d.getMonth(), d.getDate(), d.getHours(), d.getMinutes(), d.getSeconds(), d.getMilliseconds()));

            $("#SECOND_FEC_SCHE_EDIT").val(d.getSeconds());
            $("#MILLISECOND_FEC_SCHE_EDIT").val(d.getMilliseconds());
        }

        if (parseInt(@Session["ID_ACCO"]) == 3 && parseInt(@ViewBag.ID_STAT_EDIT) == 4) {
            $("#FEC_END_REAL_EDIT").kendoDateTimePicker();
            var FEC_END_REAL_EDIT = $("#FEC_END_REAL_EDIT").data("kendoDateTimePicker");
            var endReal = new Date('@ViewBag.FEC_END_REAL_EDIT');
            if ('@ViewBag.FEC_END_REAL_EDIT' != '') {
                FEC_END_REAL_EDIT.value(new Date(endReal.getFullYear(), endReal.getMonth(), endReal.getDate(), endReal.getHours(), endReal.getMinutes(), endReal.getSeconds(), endReal.getMilliseconds()));
            }
        }

    });

    function uploadDoneEditDeta(val, msg) {
        if (val == "OK") {
            swal({
                title: 'Información Guardada / Notificación Enviada',
                type: 'success',
                text: msg,
                focusConfirm: false,
                confirmButtonText:
                    'Continue',
                confirmButtonAriaLabel: 'Thumbs up, great!'

            }, function () {
                location.reload();
            })
           // $('#EditCommentModal').modal('hide');
           // winPopUpModal("Información Guardada / Notificación Enviada", "<div style='border-bottom:1px dotted #dadada;padding:0px 0px 20px 0px;'>"
           //        + "<div style='padding:10px 0px 10px 0px;'>" + msg + "</div>"
           //        + "<div style='float:right; padding:30px 0px 0px 0px; '>" +
           //        "<button id='continues' class='k-button'>Continuar</button>" +
           //        "</div></div>", 400, 160);

           // $("#continues").focus();
           // var undo = $("#continues")
           //.bind("click", function () {
           //    closeWinFormModalPopUp();
           //    closeWinModalPopUp();
           //    location.reload();
           //});

           // $("#closebtnmodal").click(function () {
           //     closeWinFormModalPopUp();
           //     closeWinModalPopUp();
           //     location.reload();
           // });
        }
        else {
            swal({
                title: 'Error al registrar',
                type: 'info',
                text: msg,
                focusConfirm: false,
                confirmButtonText:
                    'Continue',
                confirmButtonAriaLabel: 'Thumbs up, great!'

            })
            //$('#EditCommentModal').modal('hide');
            //winPopUpModal("Error al registrar", "<div style='border-bottom:1px dotted #dadada;padding:0px 0px 20px 0px;'>" +
            //   "<div style='padding:10px 0px 10px 0px;'>" + msg + "</div>" +
            //   "<div style='float:right; padding:30px 0px 0px 0px; '>" +
            //   "<button id='continuee' class='k-button'>Continuar</button>" +
            //   "</div></div>"
            //   , 400, 140);

            //$("#continuee").focus();
            //var undo = $("#continuee")
            //.bind("click", function () {
            //    closeWinModalPopUp();
            //});
        }
    }
</script>