ERPElectrodata/Models/LOCATION_ENTITY.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION_ENTITY
    {
        public int ID_LOCA { get; set; }
        public Nullable<int> ID_SITE { get; set; }
        public Nullable<int> ID_LOCA_PARENT { get; set; }
        public string NAM_LOCA { get; set; }
        public Nullable<bool> VIG_LOCA { get; set; }
        public Nullable<int> NIVEL { get; set; }
    
        public virtual SITE_ENTITY SITE_ENTITY { get; set; }
    }
}

ERPElectrodata/Controllers/Location_EntityController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERPElectrodata.Models;

namespace ERPElectrodata.Controllers
{
    public class Location_EntityController : Controller
    {
        EntityEntities dbe = new EntityEntities();
        CoreEntities dbc = new CoreEntities();
        //
        // GET: /Location_Entity/
        public ActionResult Index(int id = 0)
        {
            ViewBag.ID_SITE = id;
            return View();
        }

        public ActionResult List()
        {
            var result = (from a in dbe.LOCATION_ENTITY
                          join b in dbe.SITE_ENTITY on a.ID_SITE equals b.ID_SITE
                          select new
                          {
                              a.ID_LOCA,
                              a.NAM_LOCA,
                              b.NAM_SITE,
                              NAME = b.NAM_SITE + " - " + a.NAM_LOCA,
                          }).OrderBy(x => x.NAME);

            return Json(new { Data = result, Count = result.Count() }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Create(LOCATION_ENTITY loc_ent)
        {
            int sw = 0, ID_SITE = 0;
            string NAM_LOCA = Convert.ToString(Request.Form["NAM_LOCA"]);

            if (Int32.TryParse(Convert.ToString(Request.Form["ID_SITE"]), out ID_SITE) == false) { sw = 1; }
            else if (NAM_LOCA.Trim().Length == 0) { sw = 1; }

            if (sw == 1)
            {
                return Content("<script type='text/javascript'> function init() {" +
                    "if(top.uploadDone) top.uploadDone('ERROR','0');}window.onload=init;</script>");
            }
            try
            {
                LOCATION_ENTITY le = new LOCATION_ENTITY();
                le.ID_SITE = ID_SITE;
                le.NAM_LOCA = NAM_LOCA.ToUpper();
                le.VIG_LOCA = true;
                le.NIVEL = 1;
                dbe.LOCATION_ENTITY.Add(le);
                dbe.SaveChanges();

                string id = Convert.ToString(le.ID_LOCA);

                return Content("<script type='text/javascript'> function init() {" +
                    "if(top.uploadDone) top.uploadDone('OK','Location|" + id + "');}window.onload=init;</script>"); 
            }
            catch (Exception)
            {
                return Content("<script type='text/javascript'> function init() {" +
                    "if(top.uploadDone) top.uploadDone('ERROR','1');}window.onload=init;</script>");
            }           
        }

        public ActionResult IndexLocacion()
        {
            return View();
        }

        public ActionResult CrearLocacion()
        {
            return View();
        }
        public ActionResult EditarLocacion(int id = 0, int id1 = 0)
        {
            LOCATION location = dbc.LOCATIONs.Single(x => x.ID_LOCA == id);
            var a = dbc.ACCOUNTs.Single(x => x.ID_ACCO == id1);
            ViewBag.IdCuenta = a.ID_ACCO;
            ViewBag.Cuenta = a.NAM_ACCO;
            ViewBag.Estado = Convert.ToInt32(location.VIG_LOCA);

            return View(location);
        }

        public ActionResult ListarLocaciones(int id = 0, int id1 = 0)
        {
            var query = dbc.ListarLocaciones(id, id1).ToList();
            return Json(new { data = query }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListarSite()
        {
            string txt = "";
            int IdCuenta = Convert.ToInt32(Request.QueryString["filter[filters][0][value]"]);
            txt = Convert.ToString(Request.Params["filter[filters][1][value]"]);
            if (txt == null) { txt = ""; }

            var result = dbc.ListarSite(IdCuenta, txt).ToList();
            return Json(new { Data = result, Count = result.Count() }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost, ValidateInput(false)]

        public ActionResult Crear(LOCATION objLocacion)
        {
            int flag = 0, existe = 0;

            String IdCuenta = Convert.ToString(Request.Params["ID_ACCO"]);

            if (String.IsNullOrEmpty(IdCuenta)) { flag = 1; }
            if (String.IsNullOrEmpty(Convert.ToString(objLocacion.ID_SITE))) { flag = 2; }
            if (String.IsNullOrEmpty(objLocacion.NAM_LOCA)) { flag = 3; }

            if (flag != 0)
            {
                return Content("<script type='text/javascript'> function init() {" +
                        "if(top.uploadDone) top.uploadDone('ERROR','Por favor, complete los campos obligatorios.');}window.onload=init;</script>");
            }

            int IdSitio = Convert.ToInt32(objLocacion.ID_SITE);
            string Locacion = Convert.ToString(objLocacion.NAM_LOCA);
            var result = dbc.LOCATIONs.Where(x => x.ID_SITE == IdSitio && x.NAM_LOCA == Locacion).ToList();

            if (result.Count() > 0)
            {
                existe = 1;
            }

            if (existe != 0)
            {
                return Content("<script type='text/javascript'> function init() {" +
                        "if(top.uploadDone) top.uploadDone('EXISTE','La locación ya se encuentra registrada.');}window.onload=init;</script>");
            }

            if (ModelState.IsValid)
            {
                int IdUser = 0; //CAMBIAR POR '0'
                try
                {
                    IdUser = Convert.ToInt32(Session["UserId"].ToString());
                }
                catch
                {
                    return Content("<script type='text/javascript'> function init() {" +
                        "if(top.uploadDone) top.uploadDone('ERROR','Ha perdido la sesión.');}window.onload=init;</script>");
                }
                objLocacion.VIG_LOCA = true;
                objLocacion.NIVEL = 1;
                dbc.LOCATIONs.Add(objLocacion);
                dbc.SaveChanges();

                return Content("<script type='text/javascript'> function init() {" +
                    "if(top.uploadDone) top.uploadDone('OK','Locación registrada.');}window.onload=init;</script>");
            }
            else
            {
                return Content("<script type='text/javascript'> function init() {" +
                        "if(top.uploadDone) top.uploadDone('ERROR','Contacte al administrador.');}window.onload=init;</script>");
            }
        }


        [HttpPost, ValidateInput(false)]

        public ActionResult Editar(LOCATION objLocacion)
        {
            int flag = 0, existe = 0;

            String IdCuenta = Convert.ToString(Request.Params["ID_ACCO"]);

            if (String.IsNullOrEmpty(IdCuenta)) { flag = 1; }
            if (String.IsNullOrEmpty(Convert.ToString(objLocacion.ID_SITE))) { flag = 2; }
            if (String.IsNullOrEmpty(objLocacion.NAM_LOCA)) { flag = 3; }

            if (flag != 0)
            {
                return Content("<script type='text/javascript'> function init() {" +
                        "if(top.uploadDone) top.uploadDone('ERROR','Por favor, complete los campos obligatorios.');}window.onload=init;</script>");
            }

            int IdSitio = Convert.ToInt32(objLocacion.ID_SITE);
            int IdLocacion = Convert.ToInt32(objLocacion.ID_LOCA);
            string Locacion = Convert.ToString(objLocacion.NAM_LOCA);
            string Estado = Convert.ToString(Request.Params["Estado"]);
            var result = dbc.LOCATIONs.Where(x => x.ID_SITE == IdSitio && x.NAM_LOCA == Locacion && x.ID_LOCA != IdLocacion).ToList();

            if (result.Count() > 0)
            {
                existe = 1;
            }

            if (existe != 0)
            {
                return Content("<script type='text/javascript'> function init() {" +
                        "if(top.uploadDone) top.uploadDone('EXISTE','La locación ya se encuentra registrada.');}window.onload=init;</script>");
            }

            if (ModelState.IsValid)
            {
                int IdUser = 0; //CAMBIAR POR '0'
                try
                {
                    IdUser = Convert.ToInt32(Session["UserId"].ToString());
                }
                catch
                {
                    return Content("<script type='text/javascript'> function init() {" +
                        "if(top.uploadDone) top.uploadDone('ERROR','Ha perdido la sesión.');}window.onload=init;</script>");
                }

                Convert.ToBoolean(objLocacion.VIG_LOCA);
                dbc.LOCATIONs.Attach(objLocacion);
                dbc.Entry(objLocacion).State = EntityState.Modified;
                dbc.SaveChanges();

                return Content("<script type='text/javascript'> function init() {" +
                    "if(top.uploadDone) top.uploadDone('OK','Locación actualizada.');}window.onload=init;</script>");
            }
            else
            {
                return Content("<script type='text/javascript'> function init() {" +
                        "if(top.uploadDone) top.uploadDone('ERROR','Contacte al administrador.');}window.onload=init;</script>");
            }
        }

    }
}

ERPElectrodata/Views/Location_Entity/CrearLocacion.cshtml
@model ERPElectrodata.Models.LOCATION
@{
    ViewBag.Title = "CrearLocacion";
    Layout = null;
}

<div class="bodyForm">
    <!--Declaración de Formulario-->
    @using (Html.BeginForm("Crear", "Location_Entity", FormMethod.Post, new { enctype = "multipart/form-data", id = "FrmLocacion", target = "upload_target" }))
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <div id="mensaje"></div>

            <div class="form-group row">
                <div class="col-md-6">
                    <div class="editor-label">
                        Cuenta <b style="color:red">*</b>
                    </div>
                    <div class="editor-field">
                        <input id="ID_ACCO" type="text" name="ID_ACCO">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="editor-label">
                        Sitio <b style="color:red">*</b>
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ID_SITE)
                        @Html.ValidationMessageFor(model => model.ID_SITE)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="editor-label">
                        Nombre <b style="color:red">*</b>
                    </div>
                    <div class="k-textbox" style="min-width:100%">
                        @Html.TextBoxFor(model => model.NAM_LOCA)
                        @Html.ValidationMessageFor(model => model.NAM_LOCA)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-3">
                            <br />

                        </div>
                        <div class="col-md-3">
                            <br />

                        </div>
                        <div class="col-md-3">
                            <button id="btnCancelar" class="ladda-button mb-2 btn btn-gradient-light btn-block widthMax" data-style="expand-right" data-dismiss="modal">
                                <span class="ladda-label">Cancelar</span><span class="ladda-spinner"></span>
                            </button>

                        </div>
                        <div class="col-md-3">
                            <button id="submit" class="btn btn-warning btn-block">Guardar</button>

                        </div>
                    </div>
                    </div>
            </div>
        </fieldset>
    }
</div>
<iframe id="upload_target" name="upload_target" src="" style="width:0px;height:0px;border-width:0px;" class="display:none"></iframe>

<script type="text/javascript">
    $(document).ready(function () {

        var ID_ACCO = $("#ID_ACCO").kendoComboBox({
            autoBind: true,
            dataTextField: "NAM_ACCO",
            dataValueField: "ID_ACCO",
            filter: "contains",
            delay: 500,
            minLength: 0,
            suggest: true,
            dataSource: {
                schema: {
                    data: "Data",
                    total: "Count"
                },
                transport: {
                    read: "/TipoActivo/ListarCuentaTipoActivo?var=" + Math.random()
                }
            }
        }).data("kendoComboBox");

        var ID_SITE = $("#ID_SITE").kendoComboBox({
            autoBind: true,
            cascadeFrom: "ID_ACCO",
            dataTextField: "Site",
            dataValueField: "IdSite",
            filter: "contains",
            delay: 500,
            minLength: 0,
            suggest: true,
            dataSource: {
                serverFiltering: true,
                schema: {
                    data: "Data",
                    total: "Count"

                },
                transport: {
                    read: "/Location_Entity/ListarSite?var=" + Math.random()
                }
            }
        }).data("kendoComboBox");
    });

    //debugger
    function uploadDone(msg, msnErr) {
        if (msg == 'OK') {
            toastr.success(msnErr);
            $("#btnBuscar").click();
            $("#btnCancelar").click();
            ListarLocaciones();
        }
        else {
            toastr.error(msnErr);
        }
        /*
        if (msg == 'OK') {
            $('#modalLocacion').modal("hide");
            $('#SmallModalContent').modal("show");
            $("#SmallModalTitle").empty();
            $("#SmallModalTitle").text("Mensaje")
            $("#SmallModalBody").empty();
            $("#SmallModalBody").append("<div style='padding:10px 0 10px 0;'>" + msnErr + "</div>");
            $("#SmallModalFooter").empty();
            $("#SmallModalFooter").append("<div style='float:right;'><button id='continues' class='k-button'>Continuar</button></div>");
            var undo = $("#continues")
                .bind("click", function () {
                    $('#SmallModalContent').modal('hide');
                    $('#ModalContent').modal('hide');
                    ListarLocaciones();
                });

            $("#closebtnmodal").click(function () {
                $('#SmallModalContent').modal('hide');
                ListarLocaciones();
            });
        }
        else {
            $('#mensaje').empty();
            $('#mensaje').show("show");
            $("#mensaje").append("<div class='alert alert-danger'><strong>¡Alerta!</strong> " + msnErr + " </div>");
            setTimeout(function () {
                $("#mensaje").fadeOut(5500);
            }, 1000);

        }
        */
    }

</script>

ERPElectrodata/Views/Location_Entity/EditarLocacion.cshtml
@model ERPElectrodata.Models.LOCATION
@{
    ViewBag.Title = "EditarLocacion";
    Layout = null;
}

<link href="~/Content/themes/plugin/iCheck/square/blue.css" rel="stylesheet" />
<script src="~/Content/themes/plugin/iCheck/icheck.js"></script>

<script>
    $(document).ready(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
</script>
<div class="bodyForm">
    <!--Declaración de Formulario-->
    @using (Html.BeginForm("Editar", "Location_Entity", FormMethod.Post, new { enctype = "multipart/form-data", id = "FrmLocacion", target = "upload_target" }))
    {
        @Html.HiddenFor(model => model.ID_LOCA)
        @Html.HiddenFor(model => model.NIVEL)
        <fieldset>
            <div id="mensaje"></div>

            <div class="form-group row">
                <div class="col-md-6">
                    <div class="editor-label">
                        Cuenta <b style="color:red">*</b>
                    </div>
                    <div class="editor-field">
                        <input id="ID_ACCO" type="text" name="ID_ACCO" value="@ViewBag.IdCuenta">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="editor-label">
                        Sitio <b style="color:red">*</b>
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ID_SITE)
                        @Html.ValidationMessageFor(model => model.ID_SITE)
                    </div>
                </div>

                <div class="col-md-9">
                    <div class="editor-label">
                        Nombre <b style="color:red">*</b>
                    </div>
                    <div class="k-textbox" style="min-width:100%">
                        @Html.TextBoxFor(model => model.NAM_LOCA)
                        @Html.ValidationMessageFor(model => model.NAM_LOCA)
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="editor-label">
                        Estado
                    </div>
                    <div class="editor-field">
                        @Html.CheckBox("VIG_LOCA")
                        @Html.ValidationMessageFor(model => model.VIG_LOCA)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <button id="btnCancelar" class="ladda-button mb-2 btn btn-gradient-light btn-block widthMax" data-style="expand-right" data-dismiss="modal">
                        <span class="ladda-label">Cancelar</span><span class="ladda-spinner"></span>
                    </button>
                </div>
                <div class="col-md-6">
                    <button id="submit" class="btn btn-warning btn-block">Guardar</button>

                </div>
            </div>
        </fieldset>
    }
</div>
<iframe id="upload_target" name="upload_target" src="" style="width:0px;height:0px;border-width:0px;" class="display:none"></iframe>

<script type="text/javascript">
    $(document).ready(function () {

        if("@ViewBag.Estado"=="1"){
            $("#VIG_LOCA").attr('checked',true)
        }else{
            $("#VIG_LOCA").attr('checked',false)
        }


        var ID_ACCO = $("#ID_ACCO").kendoComboBox({
            autoBind: true,
            dataTextField: "NAM_ACCO",
            dataValueField: "ID_ACCO",
            filter: "contains",
            delay: 500,
            minLength: 0,
            suggest: true,
            dataSource: {
                schema: {
                    data: "Data",
                    total: "Count"
                },
                transport: {
                    read: "/TipoActivo/ListarCuentaTipoActivo?var=" + Math.random()
                }
            }
        }).data("kendoComboBox");

        var ID_SITE = $("#ID_SITE").kendoComboBox({
            autoBind: true,
            cascadeFrom: "ID_ACCO",
            dataTextField: "Site",
            dataValueField: "IdSite",
            filter: "contains",
            delay: 500,
            minLength: 0,
            suggest: true,
            dataSource: {
                serverFiltering: true,
                schema: {
                    data: "Data",
                    total: "Count"

                },
                transport: {
                    read: "/Location_Entity/ListarSite?var=" + Math.random()
                }
            }
        }).data("kendoComboBox");
    });


    function uploadDone(msg, msnErr) {
        if (msg == 'OK') {
            toastr.success(msnErr);
            $("#btnBuscar").click();
            $("#btnCancelar").click();
            ListarLocaciones();
        }
        else {
            toastr.error(msnErr);
        }
        /*
        if (msg == 'OK') {
            $('#modalLocacion').modal("hide");
            $('#SmallModalContent').modal("show");
            $("#SmallModalTitle").empty();
            $("#SmallModalTitle").text("Mensaje")
            $("#SmallModalBody").empty();
            $("#SmallModalBody").append("<div style='padding:10px 0 10px 0;'>" + msnErr + "</div>");
            $("#SmallModalFooter").empty();
            $("#SmallModalFooter").append("<div style='float:right;'><button id='continues' class='k-button'>Continuar</button></div>");
            var undo = $("#continues")
                .bind("click", function () {
                    $('#SmallModalContent').modal('hide');
                    $('#ModalContent').modal('hide');
                    ListarLocaciones();
                });

            $("#closebtnmodal").click(function () {
                $('#SmallModalContent').modal('hide');
                ListarLocaciones();
            });
        }
        else {
            $('#mensaje').empty();
            $('#mensaje').show("show");
            $("#mensaje").append("<div class='alert alert-danger'><strong>¡Alerta!</strong> " + msnErr + " </div>");
            setTimeout(function () {
                $("#mensaje").fadeOut(5500);
            }, 1000);

        }
        */
    }

</script>

ERPElectrodata/Views/Location_Entity/Index.cshtml
@model ERPElectrodata.Models.LOCATION_ENTITY

@{
    Layout = null;
}

@using (Html.BeginForm("Create", "Location_Entity", FormMethod.Post, new { enctype = "multipart/form-data", id = "FrmLocation_Entity", target = "upload_targetLE" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>LOCATION</legend>
            <div class="divFondoUno">
                <div class="divSpace3"></div>
                <div class="divCont3">
                    <div class="editor-label">                        
                        <a href="#" onclick="NewSite()" title="Click here to register a new Site" >@ResourceLanguaje.Resource.Site</a>
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model=>model.ID_SITE)
                        @Html.ValidationMessageFor(model => model.ID_SITE)
                    </div>
                </div>
            </div>
            <div class="divFondoDos">
                <div class="divSpace3"></div>
                <div class="divCont3">
                    <div class="editor-label">
                        @ResourceLanguaje.Resource.Location
                    </div>
                    <div class="k-textbox">
                        @Html.TextBoxFor(model=>model.NAM_LOCA)
                        @Html.ValidationMessageFor(model => model.NAM_LOCA)
                    </div>
                </div>
            </div>
            <div style="display:inline-block; float:right; padding: 15px 15px 15px 5px;">
                <div style=" float:left; padding:0px 10px 0px 0px; ">
                    <button id="submit" class="k-button">@ResourceLanguaje.Resource.BtnCreate</button>
                </div>
                <button id="cancel" class="k-button">@ResourceLanguaje.Resource.BtnCancel</button>
            </div>
    </fieldset>
}
<iframe id="upload_targetLE" name="upload_targetLE" src="" style="width:0px;height:0px;border-width:0px;" class="display:none"></iframe>

<script type="text/javascript">

    $("#submit").click(function () {
        winPopUpModalLoad("Saving Your Location", "@ResourceLanguaje.Resource.PleaseWait", 300, 130);
    });

    $("#cancel").click(function (event) {
        event.preventDefault();
        closeWinFormModalPopUp();
    });

    $("#ID_SITE").kendoComboBox({
        dataTextField: "NAM_SITE",
        dataValueField: "ID_SITE",
        filter: "contains",
        autoBind: true,
        delay: 500,
        minLength: 0,
        index: 0,
        suggest: true,
        dataSource: {
            serverFiltering: false,
            schema: {
                data: "Data",
                total: "Count"
            },
            transport: {
                read: "/Site_Entity/List?var=" + Math.random()
            }
        }
    });
    var ID_SITE = $("#ID_SITE").data("kendoComboBox");

    if ('@ViewBag.ID_SITE' != 0) {        
        ID_SITE.value(@ViewBag.ID_SITE);
    }
</script>